# Generated by Django 4.2.11 on 2024-04-19 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scotty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="payment_cash",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="payment_paypal",
        ),
    ]
