# Generated by Django 4.2.11 on 2024-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scotty", "0002_remove_profile_payment_cash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="payment_cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="payment_paypal",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
