# Generated by Django 4.2.11 on 2024-04-19 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scotty", "0003_profile_payment_cash_profile_payment_paypal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="payment_cash",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="payment_paypal",
        ),
    ]
